server:
  port: ${microservices.eureka-server.port}

spring:
  application:
    name: eureka-server
  config:
      import: optional:configserver:http://localhost:8888

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false